sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t ravi06kr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ravi06kr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-211125438593"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY